/*
 * EXT_INT_CFG.h
 *
 * Created: 02/04/2021 1:45:58 PM
 *  Author: Mark Fayez
 */ 


#ifndef EXT_INT_CFG_H_
#define EXT_INT_CFG_H_

#define GLOBAL_INTERRUPT		GLOBAL_INTERRUPT_ENABLE

#define EXTERNAL_INT0_TRIGGER	TRIGGER_RISSING
#define EXTERNAL_INT1_TRIGGER	TRIGGER_FALLING
#define EXTERNAL_INT2_TRIGGER	TRIGGER_LOW_LEVEL


#endif /* EXT_INT_CFG_H_ */